import { anthropic } from "@ai-sdk/anthropic";
import { generateObject } from "ai";
import { paramStateSchema } from "paramsSchema";
// Only include scales with seven notes, but feel free to use more esoteric scales in order to match the requested mood.
const SYSTEM_PROMPT = `
You are a music production assistant for an app that contains two synthesizers: one plays a chord progression, one plays an accompanying melody. Each synth includes a single sine, triangle, saw or square wave oscillator. The synthesizers also include low pass filters with adjustable frequency and Q. Each synth includes an ADSR envelope for the signal amplitude. Additionally, LFO parameters can be specified to modulate the oscillator frequency and filter frequency. For requests that entail a brighter sound, consider using saw or square oscillators and higher low pass filter frequencies. For more mellow sounds, use lower low pass frequencies and/or sine and triangle oscillators.

Given a prompt describing a desired vibe for a song, please respond with parameters for both synthesizers in JSON to match the prompt. Additionally, include a chord progression, scale name and root note without an octave (e.g. C). Include a melody that will be played across four bars. 

Each melody and chord progression step represents a 16th note, and are 0-indexed. Steps must include a note name and octave. For chord progressions, you can include multiple notes on each step by including multiple steps with the same startStep and endStep values. Melody steps include the start and end step plus the note including the octave (e.g. C#4). Please include 4 bars of chord progression and melody content.

When generating melodies, strongly consider using triplets and more interesting sequences vs. simple 8th note sequences.
`;
//Note: the melody will be generated by google magenta based on the chord progression you provide.
interface PromptRequest {
  prompt: string;
}

export async function POST(request: Request) {
  const { prompt }: PromptRequest = await request.json();
  if (!prompt) {
    return new Response(null, {
      status: 400,
      statusText: "Request was missing `prompt` field",
    });
  } else if (typeof prompt !== "string") {
    return new Response(null, {
      status: 400,
      statusText: "`prompt` field must be a string",
    });
  }
  if (prompt.length > 1000) {
    return new Response(null, {
      status: 400,
      statusText: "prompt length must be < 1000",
    });
  }

  try {
    const model = anthropic("claude-3-5-sonnet-20240620");
    const { object } = await generateObject({
      model,
      schema: paramStateSchema,
      system: SYSTEM_PROMPT,
      prompt: prompt,
    });
    return Response.json(object);
  } catch (e) {
    console.error(e);
    return new Response((e as any).message, { status: 500 });
  }
}
